Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Definir el generator
def my_range(n):
    i = 0
    while i < n:
        yield i
        i += 1

# Asignar a una variable
X = my_range(5)

# Recuperar el primer elemento:
print("Primer elemento:", next(X))
        
# Recuperar el resto de los elementos: 
print("Resto de los elementos")
for i in X:
    print(i)

# Tratar de recuperar otro elemento
print(next(iter, "empty"))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 20>[0;34m()[0m
[1;32m     17[0m     [38;5;28mprint[39m(i)
[1;32m     19[0m [38;5;66;03m# Tratar de recuperar otro elemento[39;00m
[0;32m---> 20[0m [38;5;28mprint[39m([38;5;28;43mnext[39;49m[43m([49m[38;5;28;43miter[39;49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mempty[39;49m[38;5;124;43m"[39;49m[43m)[49m)

[0;31mTypeError[0m: 'builtin_function_or_method' object is not an iterator
TypeError: 'builtin_function_or_method' object is not an iterator

